name: degreeworks
description: "A Flutter project for managing academic plans and courses."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Application version
version: 1.0.0+1

# Supported Flutter SDK version
environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0  # Ensure the latest version of shared_preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Includes Material Icons font for use in the project
  uses-material-design: true

  # Add fonts, images, or other project-specific files in the assets section if needed
  # Example:
  # assets:
  #   - assets/images/
  #   - assets/data/
